name: nyangmodoro
description: 집중을 도와주는 고양이 앱
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0
  flutter_riverpod: ^2.3.6
  table_calendar: ^3.0.9
  supabase_flutter: ^1.10.25
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/nyang_icon_512x512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icon/
